### PR TITLE
FEATURE: add JSFiddle and iconify playgrounds

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Signed-off-by: Ryan P.C. McQuen <ryan.q@linux.com>

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
I'm not sure we can use the icons directly from JS Bin and Plunker, but iconifying things seems to clear up the interface. The JSFiddle one is snazzy because it is already in Font Awesome. :+1:

**Comment by sanusart** [comment]
@ryanpcmcquen Maybe we can use [fontello](http://fontello.com/) to generate missing glyphs elements. Any way, I think we better incorporate this into a one menu "Open with..." with dropdown of "jsfiddle, jsbin and plunker".

**Comment by sanusart** [comment]
Yep, totaly can do with [fontello](http://fontello.com/):

image

Just need to implement the drop-down.

**Comment by ryanpcmcquen** [comment]
Wow! Great idea! Another thing I was thinking, possibly having custom "Open with's" in the settings ... maybe overkill because we have covered a few already, but in the case of JSFiddle, you could pick what framework you work in (Angular for instance).

Anyway, sounds like you have this covered. Should I close this?

**Comment by sanusart** [comment]
Maybe the framework picking can take place from the drop-down. Need to see
options.

Maybe move it to issues, but no need to close if not, lets keep for the
references.

**Pull request closed without merging**
