### PR TITLE
FEATURE add JS Bin support

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
I haven't tested this, but it seems it would work (unless Plunker support is set somewhere else).

### CODE REVIEW

**Comment by sanusart** [comment]
@ryanpcmcquen 
Referring URL need to start with http(s), otherwise it'll go to `file:///therest-of-address.here/`.

The other thing to consider: 
While JS Bin is fine for gists like [this one](https://gist.github.com/eed9cb7f0977a3e440cc), gist with multiple same extension files will not load well in JS Bin (unless I am missing something). 

Take a look at example [gist](https://gist.github.com/faf26c410c50cbce9531) with two `.html` and two `.js` files, there is no way to get to the `file1.html` or `script1.js` in this gist (something that you can do via plunkr thanks to the sidebar).

**Comment by ryanpcmcquen** [comment]
@sanusart I switched the path to http (https is supported, but is PRO only, so http is a better bet).

Not sure what to do about the lack of multi-file support, I don't think anyone would expect that to work, and it is still nice to have options, right (it isn't like Plunker is being removed)?

**Comment by sanusart** [comment]
Cool!

**Comment by ryanpcmcquen** [comment]
Thanks!

**Pull request merged**
