### PR TITLE
DOCS add Slackware install method

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Signed-off-by: Ryan P.C. McQuen <ryan.q@linux.com>

### CODE REVIEW

**Comment by sanusart** [comment]
@ryanpcmcquen 
Cool. did not knew that Slackware has this "SlackBuild".
Will you be able to maintain the package over there, or maybe we can automate it?

**Comment by ryanpcmcquen** [comment]
@sanusart, I plan on keeping it up-to-date! I maintain 154 builds over there now (we just went over 5000). The builds are tested and verified by multiple people before being approved. I have commit access for an update branch there, so I will be sure to keep gisto current, since I use it all the time.  :-)

**Comment by sanusart** [comment]
@ryanpcmcquen 
Great!!!
We recently started automating builders here. For now only nighties are 100% but we are working on automatic [release](https://github.com/Gisto/Gisto/blob/master/build/release.sh) script too. Maybe we could integrate SlackBuild package generation too.

Thank you.

**Comment by ryanpcmcquen** [comment]
That would be sweet! Thanks!

**Pull request merged**
